#!/usr/bin/env bash
# It is often convenient to edit the notebook that has been generated by
# Papermill.  Before checking the updated notebook back into source control,
# you will need to overwrite the simple python script version that was used to
# generate it.  This command will automatically clean papermill artifacts from
# the notebook and overwrite the original simple python repr.
set -euo pipefail

generated_notebook="$1"

notebook_filename=$(basename -- "$generated_notebook")
notebook_filename="${notebook_filename%.*}"

jupytext \
    --to py \
    --pipe-fmt ipynb \
    --pipe scripts/remove-papermill-metadata.sh \
    "$generated_notebook" \
    -o "notebooks/$notebook_filename.py"
